#springdoc:
#  api-docs:
#    path: /api-docs

springdoc:
  swagger-ui:
    operations-sorter: method
    groups-order: asc
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json